services:
  - type: web
    name: levanter
    runtime: docker
    branch: master
    repo: 'https://github.com/lyfe00011/whatsapp-bot-md.git'
    plan: free
    autoDeploy: true
    envVars:
      - key: SUDO
        sync: 254776728535
      - key: PREFIX
        sync: ,
      - key: STICKER_PACKNAME
        value: ',LyFE'
      - key: RMBG_KEY
        value: 'null'
      - key: WARN_LIMIT
        value: '3'
      - key: LIST_TYPE
        value: 'text'
      - key: BING_COOKIE
        value: 'null'
      - key: GEMINI_API_KEY
        value: 'null'
      - key: RENDER_NAME
        sync: gstuff
      - key: RENDER_API_KEY
        sync: rnd_pTHJj8nLMSImiJtaM0UToZgKIAWn
      - key: ANTI_DELETE
        value: 'off'
      - key: AUTO_STATUS_VIEW
        value: 'no-dl'
      - key: SEND_READ
        value: 'false'
      - key: SESSION_ID
        sync: 8_8_0e8f_4d01_3137
      - key: PORT
        value: '3000'
      - key: DATABASE_URL
        sync: postgresql://levanter_b_user:ry6ZR8a63jlYv98r8271l5sGKHv3zcJy@dpg-cqm7cso8fa8c73ccqlc0-a/levanter_b
